Online_Store/Models/ErrorViewModel.cs
namespace Online_Store.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Online_Store/Models/OrderModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Online_Store.Models
{
    public class OrderModel
    {
        public int Id { get; set; }
        [DisplayName("Product Name")]
        public string? ProductName { get; set; }
        public float Prize { get; set; }
        public List<Product>? Products { get; set; }
        [Required]
        public string? Address { get; set; }
        [DisplayName("Phone Number")]
        [Required]
        [RegularExpression(@"^\\?([0-9]{3})\)?[- ]?([0-9]{3})?[- ]?([0-9]{3})$", ErrorMessage = "The Phone Number field is not a valid phone number")]
        public string? PhoneNumber { get; set; }
    }
}

Online_Store/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Store.Models
{
    public class Product
    {
        public int Id { get; set; }

        [Required]
        public string? Name { get; set; }

        [Range(0, float.MaxValue)]
        [DataType(DataType.Currency)]
        public float Prize { get; set; }

        [Range (0, int.MaxValue)]
        [Required]
        public int Quantity { get; set; }
    }
}

Online_Store/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Store.Data;
using Online_Store.Models;

namespace Online_Store.Controllers
{
    public class CartController : Controller
    {
        public OrderModel? Order { get; set; }
        private readonly ApplicationDbContext _db;
        public CartController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var CookieList = Request.Cookies.ToList();
            var objList = new List<Product>();
            foreach(var item in CookieList)
            {
                Console.WriteLine("Value: " + item.Value);
                int id = Int32.Parse(item.Value);
                objList.Add(item: _db.Products.Find(id)!);
            }
            return View(objList);
        }
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CheckoutPost(OrderModel order)
        {
            _db.Orders.Add(order);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Online_Store/Controllers/ClientProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Store.Data;
using Online_Store.Models;

namespace Online_Store.Controllers
{
    public class ClientProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ClientProductsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Product> objList = _db.Products;
            return View(objList);
        }
        public IActionResult AddToCart(int id)
        {
            string itemID = id.ToString();
            Response.Cookies.Append("item" + itemID, itemID);
            return RedirectToAction("Index");

        }
    }
}

Online_Store/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Store.Models;
using System.Diagnostics;

namespace Online_Store.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Online_Store/Controllers/ProductsPanelController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Store.Data;
using Online_Store.Models;

namespace Online_Store.Controllers
{
    public class ProductsPanelController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProductsPanelController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Product> objList = _db.Products;
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product obj)
        {
            if(ModelState.IsValid)
            {
                _db.Products.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Products.Find(id);
            if (obj == null)
                return NotFound();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Products.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Products.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Products.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Product obj)
        {
            if (ModelState.IsValid)
            {
                _db.Products.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

Online_Store/Views/Cart/Checkout.cshtml
@model Online_Store.Models.OrderModel

<form method="post" asp-action="CheckoutPost">
    <div class="mb-3">
        <label asp-for="Address" class="form-label">Address</label>
        <input type="text" asp-for="Address" class="form-control" placeholder="Type your address for order">
        <span  asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber" class="form-label">Phone Number</label>
        <input asp-for="PhoneNumber" type="tel" class="form-control" placeholder="Type your phone number: 123456789">
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Checkout!</button>
</form>

<!-- Client-Side Validation -->
@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Online_Store/Views/Cart/Index.cshtml
@model IEnumerable<Online_Store.Models.Product>


<div class="text-center">
    <h1>CART</h1>
    @if (Model.Count() > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Item Name</th>
                    <th scope="col">Prize</th>
                </tr>
            </thead>
            <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.Name</th>
                            <td>@item.Prize</td>
                        </tr>
                    }
            </tbody>
        </table>
        <a class="btn btn-primary" asp-controller="Cart" asp-action="Checkout">Go to checkout</a>
    }
    else
    {
        <h2>Empty</h2>
    }
</div>

Online_Store/Views/ClientProducts/Index.cshtml
@model IEnumerable<Online_Store.Models.Product>

<div class="container text-center">
    <div class="row">
    @if(Model.Count() > 0)
    {
        @foreach(var item in Model)
        {
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <h6 class="card-subtitle mb-2 text-muted">@item.Prize$</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <select class="form-select" aria-label="Default select example">
                      <option selected>Quantity</option>
                      @foreach(var num in Enumerable.Range(1, item.Quantity))
                      {
                          <option id="@num" value=@num.ToString()>@num</option>

                      }
                    </select>
                    @{ //<a class="btn btn-primary mx-1" asp-controller="Home" asp-action="Index" asp-route-Id="@item.Id" asp-route-Quan="">Add To Cart</a>
                     }
                    <a class="btn btn-primary mx-1" asp-controller="ClientProducts" asp-action="AddToCart" asp-route-Id="@item.Id">Add To Cart</a>
                  </div>
                </div>
            </div>
        }
    }
    else
    {
        <p>Nothing to buy yet!</p>
    }
    </div>
</div>

Online_Store/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Online_Store/Views/ProductsPanel/Create.cshtml
@model Online_Store.Models.Product
@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border-bottom p-3">
        <div class="form-group row">
            <h2 class="text-black-50 p1-3">Add Product</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Prize"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Quantity"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input class="form-control" asp-for="Name" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="Prize" />
                        <span class="text-danger" asp-validation-for="Prize"></span>
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="Quantity" />
                        <span class="text-danger" asp-validation-for="Quantity"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-12 offset-2 row">
                        <div class="col">
                            <button type="sumbit" class="btn btn-info w-70">Create</button>
                        </div>
                        <div class="col">
                            <a class="btn btn-danger w-70" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Online_Store/Views/ProductsPanel/Delete.cshtml
@model Online_Store.Models.Product

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 p1-3">Delete Product</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Prize"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Quantity"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" disabled class="form-control"/>
                    </div>
                    <div class="col-4">
                        <input asp-for="Prize" disabled class="form-control"/> 
                    </div>
                    <div class="col-4">
                        <input asp-for="Quantity" disabled class="form-control"/>
                    </div>
                </div>
                <div class="form-group row mx-5">
                    <div class="col-12 row text-center">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-40" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-40">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Online_Store/Views/ProductsPanel/Index.cshtml
@model IEnumerable<Online_Store.Models.Product>

<div class="text-center container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Products list</h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary" asp-action="Create">Add new product</a>
        </div>
    </div>
    <br />

    @if(Model.Count() > 0)
    {
        <table class="d-lg-table table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Prize</th>
                    <th>Amount</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td width="30%">@item.Name</td>
                        <td width="30%">@item.Prize$</td>
                        <td width="30%">@item.Quantity</td>
                        <td width="25%">
                            <div class="w-100 btn-group" role="group">
                                <a class="btn btn-primary mx-1" asp-controller="ProductsPanel" asp-action="Update" asp-route-Id="@item.Id">Update</a>
                                <a class="btn btn-danger mx-1" asp-controler="ProductsPanel" asp-action="Delete" asp-route-Id="@item.Id">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No products created yet</p>
    }
</div>

Online_Store/Views/ProductsPanel/Update.cshtml
@model Online_Store.Models.Product

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 p1-3">Update Product</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Prize"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Quantity"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Prize" class="form-control"/>
                        <span asp-validation-for="Prize" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input class="form-control" asp-for="Quantity" />
                        <span class="text-danger" asp-validation-for="Quantity"></span>
                    </div>
                </div>
                <div class="form-group row mx-5">
                    <div class="col-12 row text-center">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-40" value="Update"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-40">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Client-Side Validation -->
@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Online_Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Online_Store.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsPanel" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClientProducts" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Online_Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>